parameters:
  - name: PoolStrategy
    type: object
    default: 
      - OSVmImage: azsdk-pool-mms-win-2022-1espt
        Pool: azsdk-pool-mms-win-2022-1es-pt
        os: windows
        demands: "ImageOverride -equals windows-2022"
        PythonVersion: "3.8"
        CoverageArg: --disablecov
        TestSamples: false
      - OSVmImage: azsdk-pool-mms-ubuntu-2004-1espt
        Pool: azsdk-pool-mms-ubuntu-2004-1es-pt
        os: linux
        demands: "ImageOverride -equals ubuntu-20.04"
        PythonVersion: "pypy3.9"
        CoverageArg: --disablecov
        TestSamples: false
      - OSVmImage: macos-11
        Pool: Azure Pipelines
        os: macOS
        demands: "ImageOverride -equals macos-11"
        PythonVersion: "3.11"
        CoverageArg: --disablecov
        TestSamples: false
      - OSVmImage: azsdk-pool-mms-win-2022-1espt
        Pool: azsdk-pool-mms-win-2022-1es-pt
        os: windows
        demands: "ImageOverride -equals windows-2022"
        PythonVersion: "3.10.*"
        CoverageArg: --disablecov
        TestSamples: false
      - OSVmImage: azsdk-pool-mms-ubuntu-2004-1espt
        Pool: azsdk-pool-mms-ubuntu-2004-1es-pt
        os: linux
        demands: "ImageOverride -equals ubuntu-20.04"
        PythonVersion: "3.9"
        CoverageArg: ""
        TestSamples: false
      - OSVmImage: azsdk-pool-mms-ubuntu-2004-1espt
        Pool: azsdk-pool-mms-ubuntu-2004-1es-pt
        os: linux
        demands: "ImageOverride -equals ubuntu-20.04"
        PythonVersion: "3.12"
        CoverageArg: --disablecov
        TestSamples: false

jobs:
  - ${{ each poolDefinition in parameters.PoolStrategy }}:
    - job:
      displayName: 'Test ${{ poolDefinition.os }} ${{ poolDefinition.PythonVersion }}'

      pool:
        name: azsdk-pool-mms-ubuntu-2004-general
        vmImage: "MMSUbuntu20.04"

      steps:
        - pwsh: |
            Write-Host "${{ poolDefinition.PythonVersion }}"
          displayName: Output Python Version ${{ poolDefinition.PythonVersion }}

        - task: UsePythonVersion@0
          displayName: 'Use Python ${{ poolDefinition.PythonVersion }}'
          inputs:
            versionSpec: '${{ poolDefinition.PythonVersion }}'

        - pwsh: |
            python  --version
          displayName: Dump Active Python

        - template: /eng/pipelines/templates/steps/use-python-version.yml
          parameters:
            versionSpec: '${{ poolDefinition.PythonVersion }}'

        - pwsh: |
            python  --version
          displayName: Dump Active Python
